### ISSUE TITLE
Invalid value for prop `renderer`

### ISSUE THREAD

**Issue by kkaplita** [xobotyi/react-scrollbars-custom#58]
I have an error with my customization (version 4.0.0-alpha.13):
`Invalid value for prop `renderer` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.`

Did you know to fix this?

Sample code of my component:
`wrapperProps={{
          renderer: (props) => {
            const { elementRef, ...restProps } = props;
            return <div ref={elementRef} {...restProps} className={classes.wrapper}/>;
          },
        }}`

**Comment by xobotyi** [comment]
I'll fix it in few days (probably today)

**Comment by xobotyi** [comment]
Fixed with `4.0.0-alpha.14`, recheck please.

**Comment by kkaplita** [comment]
Unfortunately not. The error is still in the version `4.0.0-alpha.14`

**Comment by xobotyi** [comment]
Could you provide a codepen or jsfiddle example please?

**Comment by kkaplita** [comment]
[https://codesandbox.io/s/7z9o4k7760](url)

**Comment by xobotyi** [comment]
Fixed with v4.0.0-alpha.15
